title: "Dilli Bhaskar"
email: "dillibhaskar05@gmail.com"
description: "Student Researcher"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Dilli-Bhaskar.github.io" # the base hostname & protocol for your site

github_username: "Dilli-Bhaskar"
linkedin_username: "dilli-bhaskar05"
